{% set name = "gruut" %}
{% set version = "2.2.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/gruut-{{ version }}.tar.gz
  sha256: 5a2da077a81776a9de3575c9fe790833b6429c7c8fa83a519e0b353ae3afa98d

build:
  number: 0
  noarch: python
  entry_points:
    - gruut = gruut.__main__:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - babel >=2.8.0,<3.0.0
    - dataclasses
    - dateparser ~=1.0.0
    - ggruut-ipa ~=0.12.0
    - gruut-lang-en
    - jsonlines ~=1.2.0
    - networkx >=2.5.0,<3.0.0
    - num2words >=0.5.10
    - numpy >=1.19.0
    - python >=3.6
    - python-crfsuite ~=0.9.7

test:
  imports:
    - gruut
  commands:
    - pip check
    - gruut --help
  requires:
    - pip

about:
  home: https://github.com/rhasspy/gruut
  summary: A tokenizer, text cleaner, and phonemizer for many human languages.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
