{% set name = "gruut" %}
{% set version = "2.0.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/gruut-{{ version }}.tar.gz
  sha256: 4e2351f3d128011e1b1570fae4219daacb5790a5211fde703e3a7db9d6e72d10

build:
  number: 0
  noarch: python
  entry_points:
    - gruut = gruut.__main__:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - babel ~=2.8.0
    - dateparser
    - gruut-ipa ~=0.10.0
    - jsonlines ~=1.2.0
    - networkx
    - num2words >=0.5.10
    - numpy >=1.19.0
    - python >=3.6
    - python-crfsuite ~=0.9.7

test:
  imports:
    - gruut
  commands:
    - pip check
    - gruut --help
  requires:
    - pip

about:
  home: https://github.com/rhasspy/gruut
  summary: A tokenizer, text cleaner, and phonemizer for many human languages.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
