{% set name = "gruut" %}
{% set version = "2.2.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/gruut-{{ version }}.tar.gz
  sha256: 8d393d5e152c1aeae62798e3c8c4cbb8a528c32fd012640db5db31194cdac6f5

build:
  number: 0
  noarch: python
  entry_points:
    - gruut = gruut.__main__:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - babel >=2.8.0,<3.0.0
    - dataclasses
    - dateparser ~=1.0.0
    - gruut-ipa ~=0.12.0
    - gruut-lang-en
    - jsonlines ~=1.2.0
    - networkx >=2.5.0,<3.0.0
    - num2words >=0.5.10
    - numpy >=1.19.0
    - python >=3.6
    - python-crfsuite ~=0.9.7

test:
  imports:
    - gruut
  commands:
    - pip check
    - gruut --help
  requires:
    - pip

about:
  home: https://github.com/rhasspy/gruut
  summary: A tokenizer, text cleaner, and phonemizer for many human languages.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
