{% set name = "gruut" %}
{% set version = "2.3.4" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/gruut-{{ version }}.tar.gz
  sha256: 7710d6fa68e4f6ab61cb0e3e98132a3aa72c3f9036c0346dfc825cded5dd1bd7

build:
  number: 0
  noarch: python
  entry_points:
    - gruut = gruut.__main__:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - babel >=2.8.0,<3.0.0
    - dataclasses
    - dateparser ~=1.1.0
    - gruut-ipa >=0.12.0,<1.0
    - gruut-lang-en ~=2.0.0
    - jsonlines ~=1.2.0
    - networkx >=2.5.0,<3.0.0
    - num2words >=0.5.10,<1.0.0
    - numpy >=1.19.0,<2.0.0
    - python >=3.6
    - python-crfsuite ~=0.9.7

test:
  imports:
    - gruut
  commands:
    - pip check
    - gruut --help
  requires:
    - pip

about:
  home: https://github.com/rhasspy/gruut
  summary: A tokenizer, text cleaner, and phonemizer for many human languages.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
