{% set name = "gruut" %}
{% set version = "1.2.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/gruut-{{ version }}.tar.gz
  sha256: ec07556359e75fc876a6b4abb0e36286fd8f467f91e57cf89e634dd894f029f9

# Placeholder
build:
  number: 0
  noarch: python
  entry_points:
    - gruut = gruut.__main__:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - babel ~=2.8.0
    - gruut-ipa ~=0.9.0
    - jsonlines ~=1.2.0
    - num2words >=0.5.10
    - python >=3.6
    - python-crfsuite ~=0.9.7

test:
  imports:
    - gruut
  commands:
    - pip check
    - gruut --help
  requires:
    - pip

about:
  home: https://github.com/rhasspy/gruut
  summary: A tokenizer, text cleaner, and phonemizer for many human languages.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
