{% set name = "gruut" %}
{% set version = "2.3.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/gruut-{{ version }}.tar.gz
  sha256: 7b3375de42b45e75945ee294f16da181c3fce739c23f77e0b7b7deeafe486028

build:
  number: 0
  noarch: python
  entry_points:
    - gruut = gruut.__main__:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - babel >=2.8.0,<3.0.0
    - dataclasses
    - dateparser ~=1.1.0
    - gruut-ipa >=0.12.0,<1.0
    - gruut-lang-en ~=2.0.0
    - jsonlines ~=1.2.0
    - networkx >=2.5.0,<3.0.0
    - num2words >=0.5.10,<1.0.0
    - numpy >=1.19.0,<2.0.0
    - python >=3.6
    - python-crfsuite ~=0.9.7

test:
  imports:
    - gruut
  commands:
    - pip check
    - gruut --help
  requires:
    - pip

about:
  home: https://github.com/rhasspy/gruut
  summary: A tokenizer, text cleaner, and phonemizer for many human languages.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
