{% set name = "gruut" %}
{% set version = "2.4.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/gruut-{{ version }}.tar.gz
  sha256: a49f693266a3a1ab5a6bde77a8f560ef27712b4169b5a6b02e6a1a873342e19e

build:
  number: 1
  noarch: python
  entry_points:
    - gruut = gruut.__main__:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - babel >=2.8.0,<3.0.0
    - dataclasses
    - dateparser ~=1.1.0
    - gruut-ipa >=0.12.0,<1.0
    - gruut-lang-en ~=2.0.0
    - jsonlines ~=1.2.0
    - networkx >=2.5.0,<3.0.0
    - num2words >=0.5.10,<1.0.0
    - numpy >=1.19.0,<2.0.0
    - python >={{ python_min }}
    - python-crfsuite ~=0.9.7

test:
  imports:
    - gruut
  commands:
    - pip check
    - gruut --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/rhasspy/gruut
  summary: A tokenizer, text cleaner, and phonemizer for many human languages.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
